new command added: exe

diff --git a/commands b/commands
--- a/commands
+++ b/commands
@@ -29,3 +29,33 @@ function push()
 	fi
 	return 0
 }
+
+function exe()
+{
+	if [ "$(ls | grep 'Makefile')" = "" ]; then # check if Makefile exists
+		printf "\033[31mexec: Makefile not found\n\033[0m"
+	else # if Makefile exists then do 'make re'
+		make re
+		if ! [ $? -eq 0 ]; then # if 'make re' fails stop the command
+			printf "\033[31mexec: makefile error\n\033[0m"
+			return $?
+		fi
+	fi
+	clear
+	local FILE=".exec.out" # temporary file
+	local exe="null" # name of the executable
+	ls -l | grep 'x' > $FILE # saves all the files with execution permissions in a new file
+	while read line; do # cycle on all the lines of $FILE
+		if ! [ "$(echo $line | head -c 1)" = "d" ]; then # the first file that's not a directory
+			exe=$(echo $line | grep -oE '[^[:space:]]+$') # is the file that will be executed
+			break
+		fi
+	done <"$FILE" # idk
+	rm -f $FILE > /dev/null 2>&1 # deletes the temporary file
+	if [ "$exe" = "null" ]; then # check if an executable was found
+		printf "\033[31mexec: no executable found\n\033[0m" # if not, stop the command
+		return 1
+	fi
+	./$exe $@ # execute the file with the parameters passed to this command
+}
+
